// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWolP0_upSu9SbbXyVH74w8epTPESt6lw',
    appId: '1:642935751205:web:1acc37271bd367a7acb5cc',
    messagingSenderId: '642935751205',
    projectId: 'batch-14-ca67e',
    authDomain: 'batch-14-ca67e.firebaseapp.com',
    storageBucket: 'batch-14-ca67e.firebasestorage.app',
    measurementId: 'G-7DFE8863BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1096mj5CyUV8OUx-E8YuQptvjqDd8gfE',
    appId: '1:642935751205:android:b307098b4b99782eacb5cc',
    messagingSenderId: '642935751205',
    projectId: 'batch-14-ca67e',
    storageBucket: 'batch-14-ca67e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ6EKbnYEzM54sIOUB6vohV1qOkBzV0UY',
    appId: '1:642935751205:ios:d85ff83bd54127e4acb5cc',
    messagingSenderId: '642935751205',
    projectId: 'batch-14-ca67e',
    storageBucket: 'batch-14-ca67e.firebasestorage.app',
    iosBundleId: 'com.example.module26assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ6EKbnYEzM54sIOUB6vohV1qOkBzV0UY',
    appId: '1:642935751205:ios:d85ff83bd54127e4acb5cc',
    messagingSenderId: '642935751205',
    projectId: 'batch-14-ca67e',
    storageBucket: 'batch-14-ca67e.firebasestorage.app',
    iosBundleId: 'com.example.module26assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWolP0_upSu9SbbXyVH74w8epTPESt6lw',
    appId: '1:642935751205:web:388fa0ee3db74f50acb5cc',
    messagingSenderId: '642935751205',
    projectId: 'batch-14-ca67e',
    authDomain: 'batch-14-ca67e.firebaseapp.com',
    storageBucket: 'batch-14-ca67e.firebasestorage.app',
    measurementId: 'G-N5XXW3XNZV',
  );
}
